"""added name to character and nullable subrace

Revision ID: 07d3d5923e6b
Revises: 18498e8c32a7
Create Date: 2024-10-09 20:39:15.742035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d3d5923e6b'
down_revision: Union[str, None] = '18498e8c32a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('characters', 'subrace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'subrace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('characters', 'name')
    op.drop_column('characters', 'level')
    # ### end Alembic commands ###
