"""remake file and db

Revision ID: 4ed6adba0c0e
Revises: cf79e1ea56c5
Create Date: 2024-10-27 00:55:55.712930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed6adba0c0e'
down_revision: Union[str, None] = 'cf79e1ea56c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artisanTools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('use', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subraces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('subrace_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('background', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['background'], ['background.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['subrace_id'], ['subraces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclassFeature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subclass_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subracesTraits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subrace_id', sa.Integer(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subrace_id'], ['subraces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('armorProficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('light', sa.Boolean(), nullable=False),
    sa.Column('medium', sa.Boolean(), nullable=False),
    sa.Column('heavy', sa.Boolean(), nullable=False),
    sa.Column('shield', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('common', sa.Boolean(), nullable=False),
    sa.Column('dwarvish', sa.Boolean(), nullable=False),
    sa.Column('elvish', sa.Boolean(), nullable=False),
    sa.Column('giant', sa.Boolean(), nullable=False),
    sa.Column('gnomish', sa.Boolean(), nullable=False),
    sa.Column('goblin', sa.Boolean(), nullable=False),
    sa.Column('halfling', sa.Boolean(), nullable=False),
    sa.Column('orc', sa.Boolean(), nullable=False),
    sa.Column('abyssal', sa.Boolean(), nullable=False),
    sa.Column('celestial', sa.Boolean(), nullable=False),
    sa.Column('deep_speech', sa.Boolean(), nullable=False),
    sa.Column('draconic', sa.Boolean(), nullable=False),
    sa.Column('infernal', sa.Boolean(), nullable=False),
    sa.Column('primordial', sa.Boolean(), nullable=False),
    sa.Column('sylvan', sa.Boolean(), nullable=False),
    sa.Column('undercommon', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savingthrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('strenght', sa.Boolean(), nullable=False),
    sa.Column('dexterity', sa.Boolean(), nullable=False),
    sa.Column('constitution', sa.Boolean(), nullable=False),
    sa.Column('intelligence', sa.Boolean(), nullable=False),
    sa.Column('wisdom', sa.Boolean(), nullable=False),
    sa.Column('charisma', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('acrobatics', sa.Boolean(), nullable=False),
    sa.Column('animal_handling', sa.Boolean(), nullable=False),
    sa.Column('arcana', sa.Boolean(), nullable=False),
    sa.Column('athletics', sa.Boolean(), nullable=False),
    sa.Column('deception', sa.Boolean(), nullable=False),
    sa.Column('history', sa.Boolean(), nullable=False),
    sa.Column('insight', sa.Boolean(), nullable=False),
    sa.Column('intimidation', sa.Boolean(), nullable=False),
    sa.Column('investigation', sa.Boolean(), nullable=False),
    sa.Column('medicine', sa.Boolean(), nullable=False),
    sa.Column('nature', sa.Boolean(), nullable=False),
    sa.Column('perception', sa.Boolean(), nullable=False),
    sa.Column('performance', sa.Boolean(), nullable=False),
    sa.Column('persuasion', sa.Boolean(), nullable=False),
    sa.Column('religion', sa.Boolean(), nullable=False),
    sa.Column('sleight_of_hand', sa.Boolean(), nullable=False),
    sa.Column('stealth', sa.Boolean(), nullable=False),
    sa.Column('survival', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('savingthrows')
    op.drop_table('languages')
    op.drop_table('armorProficiencies')
    op.drop_table('subracesTraits')
    op.drop_table('subclassFeature')
    op.drop_table('characters')
    op.drop_table('subraces')
    op.drop_table('artisanTools')
    # ### end Alembic commands ###
