"""created subraces and subraces traits table

Revision ID: 4ed75a8a01da
Revises: 385f03287f83
Create Date: 2024-03-09 17:38:43.515562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed75a8a01da'
down_revision: Union[str, None] = '385f03287f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subraces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subracesTraits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subrace_id', sa.Integer(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subrace_id'], ['subraces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subracesTraits')
    op.drop_table('subraces')
    # ### end Alembic commands ###
