"""{message}

Revision ID: 5a1d366ade3a
Revises: 932feb471f72
Create Date: 2024-10-25 02:13:57.474789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1d366ade3a'
down_revision: Union[str, None] = '932feb471f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('common', sa.Boolean(), nullable=False),
    sa.Column('dwarvish', sa.Boolean(), nullable=False),
    sa.Column('elvish', sa.Boolean(), nullable=False),
    sa.Column('giant', sa.Boolean(), nullable=False),
    sa.Column('gnomish', sa.Boolean(), nullable=False),
    sa.Column('goblin', sa.Boolean(), nullable=False),
    sa.Column('halfling', sa.Boolean(), nullable=False),
    sa.Column('orc', sa.Boolean(), nullable=False),
    sa.Column('abyssal', sa.Boolean(), nullable=False),
    sa.Column('celestial', sa.Boolean(), nullable=False),
    sa.Column('deep_speech', sa.Boolean(), nullable=False),
    sa.Column('draconic', sa.Boolean(), nullable=False),
    sa.Column('infernal', sa.Boolean(), nullable=False),
    sa.Column('primordial', sa.Boolean(), nullable=False),
    sa.Column('sylvan', sa.Boolean(), nullable=False),
    sa.Column('undercommon', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    # ### end Alembic commands ###
