"""remake char models

Revision ID: 74429beaa70c
Revises: 0855679f99c9
Create Date: 2024-11-01 22:16:54.585316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74429beaa70c'
down_revision: Union[str, None] = '0855679f99c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('strength', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('dexterity', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('constitution', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('intelligence', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('wisdom', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('charisma', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'charisma')
    op.drop_column('characters', 'wisdom')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'constitution')
    op.drop_column('characters', 'dexterity')
    op.drop_column('characters', 'strength')
    # ### end Alembic commands ###
