"""created some proficiency tables

Revision ID: 932feb471f72
Revises: d60c02cdf80e
Create Date: 2024-10-25 01:49:02.837023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932feb471f72'
down_revision: Union[str, None] = 'd60c02cdf80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savingthrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('strenght', sa.Boolean(), nullable=False),
    sa.Column('dexterity', sa.Boolean(), nullable=False),
    sa.Column('constitution', sa.Boolean(), nullable=False),
    sa.Column('intelligence', sa.Boolean(), nullable=False),
    sa.Column('wisdom', sa.Boolean(), nullable=False),
    sa.Column('charisma', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('acrobatics', sa.Boolean(), nullable=False),
    sa.Column('animal_handling', sa.Boolean(), nullable=False),
    sa.Column('arcana', sa.Boolean(), nullable=False),
    sa.Column('athletics', sa.Boolean(), nullable=False),
    sa.Column('deception', sa.Boolean(), nullable=False),
    sa.Column('history', sa.Boolean(), nullable=False),
    sa.Column('insight', sa.Boolean(), nullable=False),
    sa.Column('intimidation', sa.Boolean(), nullable=False),
    sa.Column('investigation', sa.Boolean(), nullable=False),
    sa.Column('medicine', sa.Boolean(), nullable=False),
    sa.Column('nature', sa.Boolean(), nullable=False),
    sa.Column('perception', sa.Boolean(), nullable=False),
    sa.Column('performance', sa.Boolean(), nullable=False),
    sa.Column('persuasion', sa.Boolean(), nullable=False),
    sa.Column('religion', sa.Boolean(), nullable=False),
    sa.Column('sleight_of_hand', sa.Boolean(), nullable=False),
    sa.Column('stealth', sa.Boolean(), nullable=False),
    sa.Column('survival', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('savingthrows')
    # ### end Alembic commands ###
