volumes:
  character-sheet:
    external: true

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://character:sheet@postgres/character-sheet
      # SIGNING_KEY: dh2389dh2398dh-392edh2389dh2389dh2398dh238d9h9238
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_HOST: http://localhost:8000
  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - character-sheet:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sheet
      POSTGRES_USER: character
      POSTGRES_DB: character-sheet
    ports:
      - "15432:5432"
